project_id = "nhoagucgcqjfbtifykha"

[functions.estimate-inventory]
verify_jwt = false

[functions.carrier-lookup]
verify_jwt = false

[functions.weather-route]
verify_jwt = false

[functions.google-address-validation]
verify_jwt = false

[functions.google-routes]
verify_jwt = false

[functions.google-places-insights]
verify_jwt = false

[functions.google-aerial-view]
verify_jwt = false
